Display category experts posts specially
discourse/discourse-category-experts pull request #2
Opened 2021-03-08 16:07 UTC by markvanlan

With `category_experts_posts_require_approval` enabled, category expert posts have this approve button

![image](https://user-images.githubusercontent.com/16214023/110347121-e7f15500-7ff5-11eb-868f-5e5b32757193.png)

Approved posts look like this. If `category_experts_posts_require_approval` is off, category expert posts will automatically have this styling.

![image](https://user-images.githubusercontent.com/16214023/110347229-035c6000-7ff6-11eb-8886-25757982d245.png)

2021-03-08 20:16 UTC, CvX requested changes

2021-03-08 20:16 UTC, CvX commented on assets/javascripts/discourse/initializers/category-experts-post-decorator.js
> +    next(() => {
I can't say I like scheduling a function for each post displayed and performing DOM operations manually (`querySelector`/`classList.add` – how un-ember-y 😛) but I can't think of a better solution at the moment.

2021-03-09 20:20 UTC, markvanlan commented on test/javascripts/acceptance/category-experts-post-test.js
> +      const unapproveBtn = find(
But I need it scoped within this article.. Is there a clean way to only query for children in this div otherwise?

2021-03-09 23:52 UTC, CvX commented on test/javascripts/acceptance/category-experts-post-test.js
> +      const unapproveBtn = find(
Is that `find()` scoped? 🤔
`element.querySelector` is fine too, the issue is only with the `find` function, since it isn't imported and uses jQuery.

2021-03-10 15:08 UTC, markvanlan commented on test/javascripts/acceptance/category-experts-post-test.js
> +      const unapproveBtn = find(
I thought you were talking about the query selector, not the find, woops! I can easily fix this.

2021-03-10 15:25 UTC, markvanlan commented on test/javascripts/acceptance/category-experts-post-test.js
> +      const unapproveBtn = find(
fixed!

2021-03-10 22:27 UTC, CvX approved these changes

2021-03-11 14:07 UTC, merged